#!/bin/bash
usuario=$(whoami)
pid=$(pgrep -u $usuario gnome-session | head -n 1)
dbus=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$pid/environ | tr '\0' '\n' | sed -e s/DBUS_SESSION_BUS_ADDRESS=//)
export DBUS_SESSION_BUS_ADDRESS=$dbus
export HOME=/home/$usuario
export DISPLAY=:0

carga_bat0=$(cat /sys/class/power_supply/BAT0/capacity)
carga_bat1=$(cat /sys/class/power_supply/BAT1/capacity)
bat0y1=$((( $carga_bat0 + $carga_bat1 ) / 2 ))
fuenteacdc0=$(cat /sys/class/power_supply/BAT0/status)
fuenteacdc1=$(cat /sys/class/power_supply/BAT1/status)

if  [ $bat0y1 -gt 95 ] && [ $fuenteacdc1 = "Charging" ]  ; then
    /usr/bin/notify-send --expire-time=10000 -i 'battery-full-charged' "Bateria" "Bateria0: $carga_bat0% \t\tBateria1: $carga_bat1%"

elif
    [ $bat0y1 -lt 18 ] && [ $fuenteacdc0 = "Discharging" ] ; then
    /usr/bin/notify-send --expire-time=10000 -i 'battery-caution' "Bateria" "Bateria0: $carga_bat0% \t\tBateria1: $carga_bat1%"
else
exit 0
fi
