#!/bin/bash
# link https://www.redhat.com/sysadmin/configuring-ansible
# crear script en host de control /tmp/script-reporte-usuarios.sh con el siguiente contenido:

# 1. generar lista de usuarios con bash o shell y omitiendo usuarios sshd y shutdown, e imprimiendo los campos uid y comment
grep -e bash -e sh /etc/passwd | grep -v sshd | grep -v shutd | cut -d ":" -f1,5 > /tmp/reporte-usuarios
# 2. organizar lista de usuarios 
sort /tmp/reporte-usuarios > /tmp/reporte-usuarios-uid-cm
# 3.  Generar lista con uid de cada usuario
cut -d ":" -f1 /tmp/reporte-usuarios-uid-cm > /tmp/reporte-usuarios-uid
# 4. Generar listado de usuarios pertenecientes al grupo wheel y reemplazar la coma por nueva linea
grep wheel /etc/group | cut -d ":" -f4 | sed 's/\,/\n/g' > /tmp/reporte-usuarios-su
# 5. Generar listado de usuarios com permisos ALL= en el archivo /etc/sudoers* y unirlo - añadir resultado a archivo generado en paso 4
grep -ir "ALL=" /etc/sudoers* | grep -v "#" |grep -v "%" | cut -d ":" -f2 | awk '{print $1}' >> /tmp/reporte-usuarios-su
# 6. Ordenar lista de usuarios y eliminar duplicados
sort /tmp/reporte-usuarios-su | uniq > /tmp/reporte-usuarios-sudo
# 7. iterar lista completa de usuarios contra lista de permisos con sudo y contar resultado, si es 0 no tiene sudo, si es 1 tiene sudo
for itr1 in $(cat /tmp/reporte-usuarios-uid) ; do
    grep -i $itr1 /tmp/reporte-usuarios-sudo | wc -l >> /tmp/reporte-usuarios-sudo-chk
done
# 8. unir archivo con uid + comment y archivo con validacion de sudo
paste -d : /tmp/reporte-usuarios-uid-cm /tmp/reporte-usuarios-sudo-chk > /tmp/ok-reporte-usuarios
# 9. borrar archivos temporales
rm -rvf /tmp/reporte-usuarios-* /tmp/new-reporte-usuarios-*
# 10. imprimir reporte de usuarios
cat /tmp/ok-reporte-usuarios


## llevar resultado a excel y separar texto por :
## reemplazar en columna 3 "1" por "SI"; y "0" por "NO"
##

# archivo /home/allnx/inventory
[all]
192.168.122.36

# archivo ansible.cfg
inventory      = /home/allnx/inventory
privilege_escalation]
become=True
become_method=sudo
become_user=root
become_ask_pass=False

# archivo /home/allnx/setup.yml

---
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Transfer the script
       copy: src=/tmp/script-reporte-usuarios.sh dest=/tmp/script-reporte-usuarios.sh mode=0777

     - name: Execute the script
       command: bash /tmp/script-reporte-usuarios.sh

# ejecución playbook
ansible-playbook setup.yml

# ejecución ansible ad-hoc para imprimir resultado
ansible all -m shell -a 'cat /tmp/ok-reporte-usuarios'
